#spring:
#  config:
#    activate:
#      on-profile: "prod"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testAccount
    username: postgres
    password: cdac

build:
  version: "1.9"

accounts:
  message: "Welcome to bank accounts related prod api's"
  contactDetails:
    name: "nikhil prod"
    email: "{cipher}f8d0c356e73b331756f6e7c82033b1cf30e70b8ff82aaedf6200af6706db06ae48021c765ea22b6b33e4707c426c11a0"
  onCallSupport:
    -(567)179-7389
    -(555)283-7827

