#spring:
#  config:
#    activate:
#      on-profile: "qa"

spring:
  datasource:
    url: jdbc:mysql://cardsdb:3309/cardsdb
    username: root
    password: root

build:
  version: "2.0"

cards:
  message: "Welcome to Card related qa api's"
  contactDetails:
    name: "nikhil qa"
    email: "nikhil-qa@gmail.com"
  onCallSupport:
    - "(567)553-9363"
    - "(555)523-8373"
