#spring:
#  config:
#    activate:
#      on-profile: "prod"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testAccount
    username: postgres
    password: cdac

build:
  version: "1.0"

cards:
  message: "Welcome to Card related production api's"
  contactDetails:
    name: "nikhil prod"
    email: "nikhil-prod@gmail.com"
  onCallSupport:
    -(567)179-7389
    -(555)283-7827
